[36214][1722438763048][main][info]["Booting Postman 11.6.1, linux-6.9.10-arch1-1 on x64"]
[36214][1722438763050][main][info]["EventBus~initialize - Success"]
[36214][1722438763051][main][info]["Proxy configuration has not been setup"]
[36214][1722438763051][main][info]["CloudProxyManager~init - Success"]
[36214][1722438763074][main][info]["performShellDataMigration: Starting shell data migration"]
[36214][1722438763074][main][info]["migrateShellData:Starting"]
[36214][1722438763076][main][info]["migrateShellData: Old storage cleaned up"]
[36214][1722438764840][main][info]["migrateShellData: Got data from shell. Writing to storage"]
[36214][1722438764845][main][info]["performShellDataMigration: Migration successful on try count 1"]
[36214][1722438764853][main][info]["UpdateHandler~init - Success"]
[36214][1722438764854][main][info]["LeaderSelection: Initialized successfully"]
[36214][1722438764854][main][info]["VersionDependencyService: Initialized successfully"]
[36214][1722438764862][main][info]["Generated root certificate for linux"]
[36214][1722438764864][main][info]["LinuxAutoUpdater~Cleanup - Initial cleanup successful"]
[36214][1722438764877][main][info]["GPU detected VID 4318 DID 10400 ACTIVE true"]
[36214][1722438764877][main][info]["GPU detected VID 32902 DID 18083 ACTIVE false"]
[36214][1722438764880][main][info]["newAccountRegionPreferenceService~getPreferenceWithFallback - Preference not found in storage."]
[36214][1722438764880][main][info]["newAccountRegionPreferenceService~getToggleMenuTemplate - Using preference:","useUSRegion"]
[36214][1722438764893][main][info]["shellController~init: Success"]
[36214][1722438764898][main][info]["shellMeta~init: Success"]
[36214][1722438764899][main][info]["partitionMigrationService: State of V7 partition:"]
[36214][1722438764899][main][info]["partitionMigrationService: V7 partitions",[]]
[36214][1722438764899][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"]
[36214][1722438764899][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"]
[36214][1722438764900][main][info]["partitionMigrationService~init: Success"]
[36214][1722438764905][main][info]["partitionMigrationService~runV8PartitionsIntegrity: Two way migration~ removing the following partitions from v8",[]]
[36214][1722438764909][main][info]["userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ",null]
[36214][1722438764919][main][info]["userPartitionService~init: Success"]
[36214][1722438764935][main][info]["userPartitionService: State of v8 partition system:"]
[36214][1722438764937][main][info]["shell~init~getPartitionToLoad: loading scratchpad partition"]
[36214][1722438764939][main][info]["userPartitionService: List of partitions:",[]]
[36214][1722438764939][main][info]["userPartitionService: users global meta:",{}]
[36214][1722438764970][main][info]["proxyCertificateService~ensureRootCAPresence: Deleting and creating new certificates"]
[36214][1722438764974][main][info]["Main:windowManager~newRequesterWindow: Fetch and update runtime config: undefined"]
[36214][1722438766546][main][info]["RuntimeIPCAgent~started: Success"]
[36214][1722438766554][main][info]["Main~scratchpadThemeAction:: action: set, value: dark"]
[36214][1722438766556][main][info]["Main~scratchpadThemeAction:: action: set, value: dark"]
[36214][1722438766562][main][info]["Main~scratchpadThemeAction:: action: set, value: dark"]
[36214][1722438766570][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[36214][1722438766575][main][info]["windowManager: First requester booted successfully."]
[36214][1722438766575][main][info]["windowManager~restoreWindows: Restoring requester windows"]
[36214][1722438766576][main][info]["Main~AppEvents - Received booted event for process requester.Version undefined UI Version: undefined Desktop Platform Version: 11.6.1"]
[36214][1722438768009][main][info]["Quitting app"]
[37922][1722438870760][main][info]["Booting Postman 11.6.1, linux-6.9.10-arch1-1 on x64"]
[37922][1722438870762][main][info]["EventBus~initialize - Success"]
[37922][1722438870763][main][info]["Proxy configuration has not been setup"]
[37922][1722438870763][main][info]["CloudProxyManager~init - Success"]
[37922][1722438870788][main][info]["performShellDataMigration: Migration has already been done. Bailing out"]
[37922][1722438870792][main][info]["UpdateHandler~init - Success"]
[37922][1722438870792][main][info]["LeaderSelection: Initialized successfully"]
[37922][1722438870793][main][info]["VersionDependencyService: Initialized successfully"]
[37922][1722438870796][main][info]["LinuxAutoUpdater~Cleanup - Initial cleanup successful"]
[37922][1722438872387][main][info]["GPU detected VID 4318 DID 10400 ACTIVE true"]
[38314][1722438888194][main][info]["Booting Postman 11.6.1, linux-6.9.10-arch1-1 on x64"]
[38314][1722438888195][main][info]["EventBus~initialize - Success"]
[38314][1722438888196][main][info]["Proxy configuration has not been setup"]
[38314][1722438888197][main][info]["CloudProxyManager~init - Success"]
[38314][1722438888221][main][info]["performShellDataMigration: Migration has already been done. Bailing out"]
[38314][1722438888225][main][info]["UpdateHandler~init - Success"]
[38314][1722438888226][main][info]["LeaderSelection: Initialized successfully"]
[38314][1722438888226][main][info]["VersionDependencyService: Initialized successfully"]
[38314][1722438888229][main][info]["LinuxAutoUpdater~Cleanup - Initial cleanup successful"]
[38314][1722438888240][main][info]["GPU detected VID 4318 DID 10400 ACTIVE true"]
[38314][1722438888240][main][info]["GPU detected VID 32902 DID 18083 ACTIVE false"]
[38314][1722438888242][main][info]["newAccountRegionPreferenceService~getPreferenceWithFallback - Preference not found in storage."]
[38314][1722438888242][main][info]["newAccountRegionPreferenceService~getToggleMenuTemplate - Using preference:","useUSRegion"]
[38314][1722438888253][main][info]["shellController~init: Success"]
[38314][1722438888255][main][info]["shellMeta~init: Success"]
[38314][1722438888255][main][info]["partitionMigrationService: State of V7 partition:"]
[38314][1722438888255][main][info]["partitionMigrationService: V7 partitions",[]]
[38314][1722438888255][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"]
[38314][1722438888256][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"]
[38314][1722438888256][main][info]["partitionMigrationService~init: Success"]
[38314][1722438888257][main][info]["partitionMigrationService~runV8PartitionsIntegrity: Two way migration~ removing the following partitions from v8",[]]
[38314][1722438888261][main][info]["userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ",null]
[38314][1722438888265][main][info]["userPartitionService~init: Success"]
[38314][1722438888274][main][info]["userPartitionService: State of v8 partition system:"]
[38314][1722438888276][main][info]["shell~init~getPartitionToLoad: loading scratchpad partition"]
[38314][1722438888277][main][info]["userPartitionService: List of partitions:",[{"partitionId":"f4a9bae1-af97-4e70-91ed-396cf03c9172","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]]
[38314][1722438888277][main][info]["userPartitionService: users global meta:",{}]
[38314][1722438888279][main][info]["Main:windowManager~newRequesterWindow: Fetch and update runtime config: undefined"]
[38314][1722438889680][main][info]["RuntimeIPCAgent~started: Success"]
[38314][1722438889691][main][info]["Main~scratchpadThemeAction:: action: set, value: dark"]
[38314][1722438889693][main][info]["Main~scratchpadThemeAction:: action: set, value: dark"]
[38314][1722438889702][main][info]["Main~scratchpadThemeAction:: action: set, value: dark"]
[38314][1722438889708][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[38314][1722438889713][main][info]["windowManager: First requester booted successfully."]
[38314][1722438889713][main][info]["windowManager~restoreWindows: Restoring requester windows"]
[38314][1722438889713][main][info]["Main~AppEvents - Received booted event for process requester.Version undefined UI Version: undefined Desktop Platform Version: 11.6.1"]
[38314][1722438898240][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}]
[38314][1722438898279][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:447:9)"}]
[38314][1722438898282][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}]
[38314][1722438898285][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:447:9)"}]
[38314][1722438898286][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:447:9)"}]
[38314][1722438898287][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:447:9)"}]
[38314][1722438898288][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}]
[38314][1722438898312][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:447:9)"}]
[38314][1722438898313][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}]
[38314][1722438898313][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}]
[38314][1722438898314][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}]
[38314][1722438898318][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}]
[38314][1722438898318][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:447:9)"}]
[38314][1722438898318][main][info]["sendAnalytics: Error while sending request",{"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error","stack":"ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (node:internal/deps/undici/undici:7434:28)\n    at node:internal/deps/undici/undici:7390:50\n    at Immediate._onImmediate (node:internal/deps/undici/undici:7422:13)\n    at processImmediate (node:internal/timers:476:21)"},"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:12293:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}]
[38314][1722443530796][main][info]["Quitting app"]
[38314][1722443530807][main][error]["Render process for scratchpad webview crashed",{}]
